name: PR Template Handler
on:
  pull_request:
    types: [opened]

jobs:
  apply-template:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Excute update-markdown script
        run: |
          chmod +x ./scripts/update-markdown.sh
          ./scripts/update-markdown.sh

      - name: Apply PR Template
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const { base, head } = context.payload.pull_request;

            function replaceTextInMarkdown(filePath, searchText, replaceText) {
              try {
                // อ่านไฟล์
                const content = fs.readFileSync(filePath, "utf8");

                // แทนที่ข้อความ
                const updatedContent = content.replace(
                  new RegExp(searchText, "g"),
                  replaceText
                );

                // เขียนไฟล์กลับ
                fs.writeFileSync(filePath, updatedContent, "utf8");

                console.log("แทนที่ข้อความสำเร็จ!");
                return updatedContent;
              } catch (error) {
                console.error("เกิดข้อผิดพลาด:", error);
                return null;
              }
            }

            if (head.ref.startsWith('releases/') && base.ref === 'main') {
              templateFile = '.github/PULL_REQUEST_TEMPLATE/release_to_master.md';
              templateMessage = '🚀 Release PR template automatically applied!';
            } else if (head.ref.startsWith('hotfix/') && base.ref === 'main') {
              templateFile = '.github/PULL_REQUEST_TEMPLATE/hotfix_to_master.md';
              templateMessage = '🔥 Hotfix PR template automatically applied!';
            } else if (head.ref.startsWith('releases/') && base.ref === 'dev') {
              templateFile = '.github/PULL_REQUEST_TEMPLATE/merge_down_to_develop.md'; Down
              templateMessage = '🎁 Merge Down After Release with template automatically applied!!';

              replaceTextInMarkdown('.github/PULL_REQUEST_TEMPLATE/merge_down_to_develop.md', '{{RELEASE_VERSION}}', head.ref.replace('releases/', ''));
              replaceTextInMarkdown('.github/PULL_REQUEST_TEMPLATE/merge_down_to_develop.md', '{{FROM}}', base.ref);


            } else if (base.ref === 'dev') {
              templateFile = '.github/PULL_REQUEST_TEMPLATE/feature_to_develop.md';
              templateMessage = '✨ Feature PR template automatically applied!';
            }  else {
              console.log('No matching branch pattern found for PR template');
              return;
            }

            try {
              // Check if template file exists
              if (!fs.existsSync(templateFile)) {
                console.log(`Template file does not exist: ${templateFile}`);
                return;
              }
              
              // Read the template content
              const templateContent = fs.readFileSync(templateFile, 'utf8');
              
              // Update the PR description with the template content
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: templateContent
              });
              
              // Add a comment to notify the user
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: templateMessage
              });
              
              console.log(`Applied PR template: ${templateFile}`);
            } catch (error) {
              console.error(`Error applying PR template: ${error}`);
            }
