name: Reusable Workflow

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      level:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print my tags
        run: echo "${{ inputs.tags}}"
      - name: Print my level
        run: echo "${{ inputs.level}}"
      - name: Print my environment
        run: echo "${{ inputs.environment}}"
